In [1]:
import torch
#creating a tensors
t1=torch.tensor([1,2,3,4])
t2=torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
#printing the tensors:
print("Tensor t1: \n",t1)
print("\ntensor t2:\n",t2)
#rank of tensors:
print("\nRank of t1:",len(t1.shape))
print("Rank of t2:",len(t2.shape))
#shape of tensors
print("\nRank of t1:",t1.shape)
print("Rank of t2:",t2.shape)

Tensor t1: 
 tensor([1, 2, 3, 4])

tensor t2:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

Rank of t1: 1
Rank of t2: 2

Rank of t1: torch.Size([4])
Rank of t2: torch.Size([3, 4])


In [2]:
import torch
import numpy as np
#list of values to be stored as tensor
data1=[1,2,3,4,5,6]
data2=np.array([1,2,3,4,6.8,9.3,7.0,2.8])
#creating tensors and printing
t1=torch.tensor(data1)
t2=torch.tensor(data1)
t3=torch.tensor(data2)
t4=torch.from_numpy(data2)
print("Tensor:",t1,"Data type:",t1.dtype,"\n")
print("Tensor:",t2,"Data type:",t2.dtype,"\n")
print("Tensor:",t3,"Data type:",t3.dtype,"\n")
print("Tensor:",t4,"Data type:",t4.dtype,"\n")

Tensor: tensor([1, 2, 3, 4, 5, 6]) Data type: torch.int64 

Tensor: tensor([1, 2, 3, 4, 5, 6]) Data type: torch.int64 

Tensor: tensor([1.0000, 2.0000, 3.0000, 4.0000, 6.8000, 9.3000, 7.0000, 2.8000],
       dtype=torch.float64) Data type: torch.float64 

Tensor: tensor([1.0000, 2.0000, 3.0000, 4.0000, 6.8000, 9.3000, 7.0000, 2.8000],
       dtype=torch.float64) Data type: torch.float64 



In [3]:
import torch
#defining tensor
t=torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
#reshaping the tensor
print("Reshaping")
print(t.reshape(6,2))
#resizing the tensor
print("\nResizing")
print(t.resize(2,6))
#transposing the tensor
print("\nTransposing")
print(t.transpose(1,0))

Reshaping
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])

Resizing
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

Transposing
tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])


/usr/local/lib/python3.10/dist-packages/torch/_tensor.py:955: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


In [4]:
import torch
#defining two tensors
t1=torch.tensor([1,2,3,4])
t2=torch.tensor([5,6,7,8])
#adding two tensors
print("tensor2+tensor1")
print(torch.add(t2,t1))
#subtracting two tensor
print("\ntensor2-tensor1")
print(torch.sub(t2,t1))
#multiplying two tensors
print("\ntensor2*tensor1")
print(torch.mul(t2,t1))
#dividing two tensors
print("\ntensor2/tensor1")
print(torch.div(t2,t1))

tensor2+tensor1
tensor([ 6,  8, 10, 12])

tensor2-tensor1
tensor([4, 4, 4, 4])

tensor2*tensor1
tensor([ 5, 12, 21, 32])

tensor2/tensor1
tensor([5.0000, 3.0000, 2.3333, 2.0000])


In [5]:
import torch
#creating a tensor
t1=torch.tensor(1.0,requires_grad=True)
t2=torch.tensor(2.0,requires_grad=True)
#creating a variable and gradient
z=100*t1*t2
z.backward()
#printing gradient
print("dz/dt1:",t1.grad.data)
print("dz/dt2:",t2.grad.data)

dz/dt1: tensor(200.)
dz/dt2: tensor(100.)
