In [1]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [2]:
#First create a scalar using tf.constant
scalar=tf.constant(7)
print(scalar)
print(scalar.ndim)

tf.Tensor(7, shape=(), dtype=int32)
0


In [3]:
#create a vector
vector=tf.constant([10,10])
print(vector)
print(vector.ndim)

tf.Tensor([10 10], shape=(2,), dtype=int32)
1


In [4]:
#creating matrix
matrix=tf.constant([[10,11],[12,13]])
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[10 11]
 [12 13]], shape=(2, 2), dtype=int32)
2


In [5]:
#Simple calculation using tensor
basic_tensor=tf.constant([[10,11],[12,13]])
print(basic_tensor)

tf.Tensor(
[[10 11]
 [12 13]], shape=(2, 2), dtype=int32)


In [6]:
# add, substract, multiply, divide
print(basic_tensor+10)
print(basic_tensor-10)
print(basic_tensor*10)
print(basic_tensor/10)

tf.Tensor(
[[20 21]
 [22 23]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0 1]
 [2 3]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100 110]
 [120 130]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1.  1.1]
 [1.2 1.3]], shape=(2, 2), dtype=float64)


In [7]:
#matrix multiplication
tensor_011=tf.constant([[2,2],[4,4]])
tensor_012=tf.constant([[2,3],[4,5]])
print(tf.matmul(tensor_011, tensor_012))

tf.Tensor(
[[12 16]
 [24 32]], shape=(2, 2), dtype=int32)


In [8]:
#To find max and min value
tensor_013=tf.constant([[1,2,3],[4,5,6],[7,8,9]], dtype='float32')
print(tf.reduce_min(tensor_013))
print(tf.reduce_max(tensor_013))
print(tf.reduce_sum(tensor_013))

tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(9.0, shape=(), dtype=float32)
tf.Tensor(45.0, shape=(), dtype=float32)


In [9]:
#square, square root, and log
print(tf.square(tensor_013))
print(tf.sqrt(tensor_013))
print(tf.math.log(tensor_013))

tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]
 [49. 64. 81.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1.        1.4142135 1.7320508]
 [2.        2.236068  2.4494898]
 [2.6457512 2.828427  3.       ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.        0.6931472 1.0986123]
 [1.3862944 1.609438  1.7917595]
 [1.9459102 2.0794415 2.1972246]], shape=(3, 3), dtype=float32)
